apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-desafio-k8s
spec: # spec deployment
  replicas: 1
  selector:
    matchLabels:
      app: go-desafio-k8s
  template:
    metadata:
      labels:
        app: go-desafio-k8s
    spec: #spec container
      containers:
        - name: go-ws
          image: pereiraze/go-desafio-k8s:latest
          ports:
            - containerPort: 8000
